version: "3.1"

services:
  test-postgres:
    env_file: docker/.env
    image: postgres:13.2
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

