# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_pass
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false

logging:
  level:
    ROOT: info
    org.springframework: warn
    com.example.demo: debug

server:
  port: 8082
  error:
    include-message: always


